# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iLimbGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbSerial = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSerial.setGeometry(QtCore.QRect(10, 30, 151, 101))
        self.gbSerial.setObjectName("gbSerial")
        self.gridLayout = QtWidgets.QGridLayout(self.gbSerial)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gbSerial)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cbSerialPort = QtWidgets.QComboBox(self.gbSerial)
        self.cbSerialPort.setObjectName("cbSerialPort")
        self.gridLayout.addWidget(self.cbSerialPort, 1, 0, 1, 1)
        self.btnSerialConnect = QtWidgets.QPushButton(self.gbSerial)
        self.btnSerialConnect.setObjectName("btnSerialConnect")
        self.gridLayout.addWidget(self.btnSerialConnect, 2, 0, 1, 1)
        self.gbFingers = QtWidgets.QGroupBox(self.centralwidget)
        self.gbFingers.setGeometry(QtCore.QRect(20, 140, 241, 271))
        self.gbFingers.setObjectName("gbFingers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbFingers)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chRing = QtWidgets.QCheckBox(self.gbFingers)
        self.chRing.setObjectName("chRing")
        self.gridLayout_2.addWidget(self.chRing, 3, 0, 1, 1)
        self.cbRing = QtWidgets.QComboBox(self.gbFingers)
        self.cbRing.setObjectName("cbRing")
        self.gridLayout_2.addWidget(self.cbRing, 3, 1, 1, 1)
        self.chThumb = QtWidgets.QCheckBox(self.gbFingers)
        self.chThumb.setObjectName("chThumb")
        self.gridLayout_2.addWidget(self.chThumb, 0, 0, 1, 1)
        self.cbThumb = QtWidgets.QComboBox(self.gbFingers)
        self.cbThumb.setObjectName("cbThumb")
        self.gridLayout_2.addWidget(self.cbThumb, 0, 1, 1, 1)
        self.spThumb = QtWidgets.QSpinBox(self.gbFingers)
        self.spThumb.setObjectName("spThumb")
        self.gridLayout_2.addWidget(self.spThumb, 0, 2, 1, 1)
        self.cbIndex = QtWidgets.QComboBox(self.gbFingers)
        self.cbIndex.setObjectName("cbIndex")
        self.gridLayout_2.addWidget(self.cbIndex, 1, 1, 1, 1)
        self.chMiddle = QtWidgets.QCheckBox(self.gbFingers)
        self.chMiddle.setObjectName("chMiddle")
        self.gridLayout_2.addWidget(self.chMiddle, 2, 0, 1, 1)
        self.spIndex = QtWidgets.QSpinBox(self.gbFingers)
        self.spIndex.setObjectName("spIndex")
        self.gridLayout_2.addWidget(self.spIndex, 1, 2, 1, 1)
        self.cbMiddle = QtWidgets.QComboBox(self.gbFingers)
        self.cbMiddle.setObjectName("cbMiddle")
        self.gridLayout_2.addWidget(self.cbMiddle, 2, 1, 1, 1)
        self.chIndex = QtWidgets.QCheckBox(self.gbFingers)
        self.chIndex.setObjectName("chIndex")
        self.gridLayout_2.addWidget(self.chIndex, 1, 0, 1, 1)
        self.spMiddle = QtWidgets.QSpinBox(self.gbFingers)
        self.spMiddle.setObjectName("spMiddle")
        self.gridLayout_2.addWidget(self.spMiddle, 2, 2, 1, 1)
        self.spRing = QtWidgets.QSpinBox(self.gbFingers)
        self.spRing.setObjectName("spRing")
        self.gridLayout_2.addWidget(self.spRing, 3, 2, 1, 1)
        self.chLittle = QtWidgets.QCheckBox(self.gbFingers)
        self.chLittle.setObjectName("chLittle")
        self.gridLayout_2.addWidget(self.chLittle, 4, 0, 1, 1)
        self.cbLittle = QtWidgets.QComboBox(self.gbFingers)
        self.cbLittle.setObjectName("cbLittle")
        self.gridLayout_2.addWidget(self.cbLittle, 4, 1, 1, 1)
        self.spLittle = QtWidgets.QSpinBox(self.gbFingers)
        self.spLittle.setObjectName("spLittle")
        self.gridLayout_2.addWidget(self.spLittle, 4, 2, 1, 1)
        self.cbThumbRotator = QtWidgets.QComboBox(self.gbFingers)
        self.cbThumbRotator.setObjectName("cbThumbRotator")
        self.gridLayout_2.addWidget(self.cbThumbRotator, 5, 1, 1, 1)
        self.chThumbRotator = QtWidgets.QCheckBox(self.gbFingers)
        self.chThumbRotator.setObjectName("chThumbRotator")
        self.gridLayout_2.addWidget(self.chThumbRotator, 5, 0, 1, 1)
        self.spThumbRotator = QtWidgets.QSpinBox(self.gbFingers)
        self.spThumbRotator.setObjectName("spThumbRotator")
        self.gridLayout_2.addWidget(self.spThumbRotator, 5, 2, 1, 1)
        self.btnControlFingers = QtWidgets.QPushButton(self.gbFingers)
        self.btnControlFingers.setObjectName("btnControlFingers")
        self.gridLayout_2.addWidget(self.btnControlFingers, 7, 0, 1, 3)
        self.chWrist = QtWidgets.QCheckBox(self.gbFingers)
        self.chWrist.setObjectName("chWrist")
        self.gridLayout_2.addWidget(self.chWrist, 6, 0, 1, 1)
        self.cbWrist = QtWidgets.QComboBox(self.gbFingers)
        self.cbWrist.setObjectName("cbWrist")
        self.gridLayout_2.addWidget(self.cbWrist, 6, 1, 1, 1)
        self.spWrist = QtWidgets.QSpinBox(self.gbFingers)
        self.spWrist.setObjectName("spWrist")
        self.gridLayout_2.addWidget(self.spWrist, 6, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 150, 171, 101))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 42, 23, 16))
        self.label_2.setObjectName("label_2")
        self.cbPoses = QtWidgets.QComboBox(self.groupBox)
        self.cbPoses.setGeometry(QtCore.QRect(42, 42, 111, 20))
        self.cbPoses.setObjectName("cbPoses")
        self.btnPoses = QtWidgets.QPushButton(self.groupBox)
        self.btnPoses.setGeometry(QtCore.QRect(10, 70, 141, 23))
        self.btnPoses.setObjectName("btnPoses")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 538, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iLimb GUI Control"))
        self.gbSerial.setTitle(_translate("MainWindow", "iLimb Serial Port Config"))
        self.label.setText(_translate("MainWindow", "Port name"))
        self.btnSerialConnect.setText(_translate("MainWindow", "Connect"))
        self.gbFingers.setTitle(_translate("MainWindow", "iLimb Control Fingers"))
        self.chRing.setText(_translate("MainWindow", "Ring"))
        self.chThumb.setText(_translate("MainWindow", "Thumb"))
        self.chMiddle.setText(_translate("MainWindow", "Middle"))
        self.chIndex.setText(_translate("MainWindow", "Index"))
        self.chLittle.setText(_translate("MainWindow", "Little"))
        self.chThumbRotator.setText(_translate("MainWindow", "thRotator"))
        self.btnControlFingers.setText(_translate("MainWindow", "Send Control"))
        self.chWrist.setText(_translate("MainWindow", "Wrist"))
        self.groupBox.setTitle(_translate("MainWindow", "iLimb Poses"))
        self.label_2.setText(_translate("MainWindow", "Pose"))
        self.btnPoses.setText(_translate("MainWindow", "Send Pose"))

