# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'URGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.groupBox)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_2.addWidget(self.btnConnect, 2, 0, 1, 2)
        self.tbIP = QtWidgets.QLineEdit(self.groupBox)
        self.tbIP.setObjectName("tbIP")
        self.gridLayout_2.addWidget(self.tbIP, 0, 1, 1, 1)
        self.tbPort = QtWidgets.QLineEdit(self.groupBox)
        self.tbPort.setObjectName("tbPort")
        self.gridLayout_2.addWidget(self.tbPort, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.tbRy = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbRy.setObjectName("tbRy")
        self.gridLayout.addWidget(self.tbRy, 4, 1, 1, 1)
        self.tbRz = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbRz.setObjectName("tbRz")
        self.gridLayout.addWidget(self.tbRz, 5, 1, 1, 1)
        self.tbRx = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbRx.setObjectName("tbRx")
        self.gridLayout.addWidget(self.tbRx, 3, 1, 1, 1)
        self.tbTime = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbTime.setObjectName("tbTime")
        self.gridLayout.addWidget(self.tbTime, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.btnMove = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMove.setObjectName("btnMove")
        self.gridLayout.addWidget(self.btnMove, 7, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.tbX = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbX.setText("")
        self.tbX.setObjectName("tbX")
        self.gridLayout.addWidget(self.tbX, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.tbZ = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbZ.setObjectName("tbZ")
        self.gridLayout.addWidget(self.tbZ, 2, 1, 1, 1)
        self.tbBase = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbBase.setObjectName("tbBase")
        self.gridLayout.addWidget(self.tbBase, 9, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.tbY = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbY.setText("")
        self.tbY.setObjectName("tbY")
        self.gridLayout.addWidget(self.tbY, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.tbShoulder = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbShoulder.setObjectName("tbShoulder")
        self.gridLayout.addWidget(self.tbShoulder, 10, 1, 1, 1)
        self.tbWrist1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbWrist1.setObjectName("tbWrist1")
        self.gridLayout.addWidget(self.tbWrist1, 13, 1, 1, 1)
        self.tbElbow = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbElbow.setObjectName("tbElbow")
        self.gridLayout.addWidget(self.tbElbow, 11, 1, 1, 1)
        self.tbWrist3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbWrist3.setObjectName("tbWrist3")
        self.gridLayout.addWidget(self.tbWrist3, 17, 1, 1, 1)
        self.tbWrist2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tbWrist2.setObjectName("tbWrist2")
        self.gridLayout.addWidget(self.tbWrist2, 14, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 14, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 17, 0, 1, 1)
        self.btnMoveJoints = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMoveJoints.setObjectName("btnMoveJoints")
        self.gridLayout.addWidget(self.btnMoveJoints, 23, 0, 1, 2)
        self.label_3.raise_()
        self.tbX.raise_()
        self.label_4.raise_()
        self.tbY.raise_()
        self.label_5.raise_()
        self.tbZ.raise_()
        self.label_6.raise_()
        self.tbRx.raise_()
        self.label_7.raise_()
        self.tbRy.raise_()
        self.label_8.raise_()
        self.tbRz.raise_()
        self.btnMove.raise_()
        self.tbTime.raise_()
        self.label_9.raise_()
        self.label_12.raise_()
        self.label_10.raise_()
        self.tbBase.raise_()
        self.label_11.raise_()
        self.tbWrist1.raise_()
        self.tbElbow.raise_()
        self.tbShoulder.raise_()
        self.tbWrist2.raise_()
        self.tbWrist3.raise_()
        self.btnMoveJoints.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tbStatus = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.tbStatus.setObjectName("tbStatus")
        self.gridLayout_3.addWidget(self.tbStatus, 0, 0, 1, 1)
        self.btnAddJoint = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAddJoint.setObjectName("btnAddJoint")
        self.gridLayout_3.addWidget(self.btnAddJoint, 6, 0, 1, 1)
        self.btnAddPosition = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAddPosition.setObjectName("btnAddPosition")
        self.gridLayout_3.addWidget(self.btnAddPosition, 5, 0, 1, 1)
        self.lbPoses = QtWidgets.QListWidget(self.groupBox_3)
        self.lbPoses.setObjectName("lbPoses")
        self.gridLayout_3.addWidget(self.lbPoses, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.tbName = QtWidgets.QLineEdit(self.groupBox_3)
        self.tbName.setObjectName("tbName")
        self.gridLayout_3.addWidget(self.tbName, 4, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_3.addWidget(self.btnSave, 7, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UR10 GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "UR10 Config"))
        self.label_2.setText(_translate("MainWindow", "PORT"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.groupBox_2.setTitle(_translate("MainWindow", "UR10 Movement"))
        self.label_8.setText(_translate("MainWindow", "RZ"))
        self.label_12.setText(_translate("MainWindow", "Elbow"))
        self.label_7.setText(_translate("MainWindow", "RY"))
        self.btnMove.setText(_translate("MainWindow", "Move"))
        self.label_9.setText(_translate("MainWindow", "Time"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.label_3.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "RX"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.label_11.setText(_translate("MainWindow", "Shoulder"))
        self.label_10.setText(_translate("MainWindow", "Base"))
        self.label_13.setText(_translate("MainWindow", "Wrist 1"))
        self.label_14.setText(_translate("MainWindow", "Wrist 2"))
        self.label_15.setText(_translate("MainWindow", "Wrist 3"))
        self.btnMoveJoints.setText(_translate("MainWindow", "Move Joints"))
        self.groupBox_3.setTitle(_translate("MainWindow", "UR10 Status"))
        self.btnAddJoint.setText(_translate("MainWindow", "Add Joints"))
        self.btnAddPosition.setText(_translate("MainWindow", "Add Position"))
        self.label_16.setText(_translate("MainWindow", "Positions/Joints"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.label_17.setText(_translate("MainWindow", "Name of position/joint"))

