#ifndef ERRORS_H
#define ERRORS_H

typedef enum
{
	LDA_OK = 0,
	LDA_FLASH_WRITE_ERROR = 1,
	LDA_FLASH_READ_ERROR = 2,
	LDA_FLASH_ERASE_ERROR = 3,
	LDA_ELEMENT_NOT_FOUND = 4,
	LDA_CONFIG_NOT_INITIALIZED = 5,
	LDA_CONFIG_NULL_PTR = 6,
	LDA_INDEX_BOUNDS_ERROR = 7,
	LDA_BOUNDS_ERROR = 8,
	LDA_INVALID_HAND_TYPE = 9,
	LDA_INVALID_GRIP_TYPE = 10,
	LDA_I2C_SLAVE_NOT_INITIALIZED = 11,
	LDA_ERROR_NULL_PTR = 12,
	LDA_VIBE_ALREADY_INITIALIZED = 13,
	LDA_VIBE_NOT_INITIALIZED = 14,
	LDA_VIBE_INVALID_STATE = 15,
	LDA_VIBE_BUFFER_FULL = 16,
	LDA_ELECTRODE_ERROR = 17,
	LDA_ELECTRODE_MAX_RETRY_ERROR = 18,
	LDA_ACC_BIT_FAILED = 19,
	LDA_ELECTRODE_BIT_FAILED = 20,
	LDA_FM_BIT_FAILED = 21,
	LDA_DAC_BIT_FAILED = 22,
	LDA_RC_BIT_FAILED = 23,
	LDA_ERROR = 24
} ReturnCode;

#endif //ERRORS_H